server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: ingestion-service
  flyway:
    enabled: ${SPRING_FLYWAY_ENABLED:true}
    locations: ${SPRING_FLYWAY_LOCATIONS:classpath:db/migration}
    url: ${SPRING_FLYWAY_URL:jdbc:postgresql://localhost:5432/dataplatform}
    user: ${SPRING_FLYWAY_USER:dataplatform}
    password: ${SPRING_FLYWAY_PASSWORD:dataplatform}

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus

app:
  s3:
    enabled: ${S3_ENABLED:false}
  kinesis:
    enabled: ${KINESIS_ENABLED:false}
  aws:
    region: ${AWS_REGION:us-east-1}
    endpoint-override: ${AWS_ENDPOINT_OVERRIDE:}
    kinesis-stream-name: ${KINESIS_STREAM_NAME:payment-events-stream}
    data-lake-bucket: ${DATA_LAKE_BUCKET:data-platform-lake}
  schema:
    path: ${SCHEMA_PATH:shared/schemas/payment/v1.json}
